const TelegramBot = require("node-telegram-bot-api");
const express = require("express");
const axios = require("axios");

const { checkNFT } = require("./nftCheck");

const BOT_TOKEN = process.env.BOT_TOKEN;

const bot = new TelegramBot(BOT_TOKEN, { polling: true });

const app = express();
app.use(express.json());

// TEMP storage
const verifiedUsers = {};

// START
bot.onText(/\/start/, (msg) => {
  bot.sendMessage(
    msg.chat.id,
    `👛 NFT Verification Required

Send your TON wallet using:

/wallet YOUR_WALLET_ADDRESS

After verification you can use:

/img your prompt`
  );
});

// NFT VERIFY COMMAND
bot.onText(/\/wallet (.+)/, async (msg, match) => {
  const chatId = msg.chat.id;
  const wallet = match[1];

  bot.sendMessage(chatId, "🔍 Checking NFT ownership...");

  const isOwner = await checkNFT(wallet);

  if (isOwner) {
    verifiedUsers[chatId] = true;

    return bot.sendMessage(
      chatId,
      "✅ NFT verified successfully!\nYou can now use /img"
    );
  }

  return bot.sendMessage(
    chatId,
    "❌ Required NFT not found in this wallet."
  );
});

// IMAGE COMMAND
bot.onText(/\/img (.+)/, async (msg, match) => {
  const chatId = msg.chat.id;
  const prompt = match[1];

  if (!verifiedUsers[chatId]) {
    return bot.sendMessage(
      chatId,
      "❌ You are not verified.\nUse /wallet first."
    );
  }

  const url =
    `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}`;

  bot.sendPhoto(chatId, url, {
    caption: "🎨 Generated by AI"
  });
});

// OPTIONAL VERIFY API ROUTE
app.post("/verify", (req, res) => {
  const { tg_id } = req.body;

  verifiedUsers[tg_id] = true;

  res.json({ success: true });
});

app.listen(3000, () => {
  console.log("Bot running");
});
