const TelegramBot = require("node-telegram-bot-api");
const express = require("express");
const axios = require("axios");

const BOT_TOKEN = process.env.BOT_TOKEN;
const bot = new TelegramBot(BOT_TOKEN, { polling: true });

const app = express();
app.use(express.json());

// TEMP storage (later upgrade to DB)
const verifiedUsers = {};

// START
bot.onText(/\/start/, (msg) => {
  bot.sendMessage(msg.chat.id,
    "👛 Connect wallet first (TON NFT required)\nThen use /img prompt",
  );
});

// IMAGE COMMAND
bot.onText(/\/img (.+)/, async (msg, match) => {
  const chatId = msg.chat.id;
  const prompt = match[1];

  if (!verifiedUsers[chatId]) {
    return bot.sendMessage(chatId, "❌ Not verified (NFT required)");
  }

  const url = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}`;

  bot.sendPhoto(chatId, url, {
    caption: "🎨 Generated by AI"
  });
});

// SIMPLE VERIFY (temporary manual test)
app.post("/verify", (req, res) => {
  const { tg_id } = req.body;
  verifiedUsers[tg_id] = true;

  res.json({ success: true });
});

app.listen(3000, () => {
  console.log("Bot running");
});
